name: Upload install scripts
on:
  push:
  pull_request:

jobs:
  test-unix:
    strategy:
      matrix:
        os: [ubuntu-slim, macos-latest]
        version: [stable, staged]
    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.version }} ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7

    - name: Test staged Unix install
      if: matrix.version == 'staged'
      shell: bash
      run: |
        DUCKDB_STAGED=c99ade5cb6/v2.0.0-alpha38367 bash install.sh
        ALPHA_INST="$HOME/.duckdb/cli/v2.0.0-alpha38367"
        test -x "$ALPHA_INST/duckdb"
        test "$(readlink ~/.duckdb/cli/latest)" = "$ALPHA_INST"
        ~/.duckdb/cli/latest/duckdb -c "select 42"

    - name: Test stable Unix install
      shell: bash
      run: |
        cat install.sh | bash
        ~/.duckdb/cli/latest/duckdb -c "select 42"

  test-windows:
    strategy:
      matrix:
        version: [stable, staged]
    runs-on: windows-latest
    name: Test ${{ matrix.version }} windows-latest
    steps:
    - uses: actions/checkout@v7

    - name: Test stable Windows install
      if: matrix.version == 'stable'
      shell: pwsh
      run: |
        ./install.ps1
        $sh = New-Object -ComObject WScript.Shell
        $target = $sh.CreateShortcut("$Home\Desktop\DuckDB.lnk").TargetPath
        & $target -c "select 42"

    - name: Test staged Windows install
      if: matrix.version == 'staged'
      shell: pwsh
      run: |
        $env:DUCKDB_STAGED = "c99ade5cb6/v2.0.0-alpha38367"
        ./install.ps1
        & "$env:LOCALAPPDATA\duckdb\cli\v2.0.0-alpha38367\duckdb.exe" -c "select 42"

  upload:
    needs: [test-unix, test-windows]
    runs-on: ubuntu-slim
    if: github.repository == 'duckdb/duckdb-install-scripts' && github.ref_name == 'main'

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install
        shell: bash
        run: pip install awscli

      - name: Upload
        env:
          AWS_ENDPOINT_URL: ${{ secrets.DUCKDB_INSTALL_S3_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DUCKDB_INSTALL_S3_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DUCKDB_INSTALL_S3_SECRET }}

        shell: bash
        run: |
          aws s3 cp install.sh s3://duckdb-install/
          aws s3 cp install.ps1 s3://duckdb-install/
