name: Upload install scripts
on:
  push:


jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-slim
            name: Linux (stable)
            command: |
              cat install.sh | bash
              ~/.duckdb/cli/latest/duckdb -c "select 42"
          - os: ubuntu-slim
            name: Linux (staged)
            command: |
              DUCKDB_STAGED=c99ade5cb6/v2.0.0-alpha38367 bash install.sh
              test -x ~/.duckdb/cli/v2.0.0-alpha38367/duckdb
              ~/.duckdb/cli/latest/duckdb -c "select 42"
          - os: macos-latest
            name: macOS (stable)
            command: |
              cat install.sh | bash
              ~/.duckdb/cli/latest/duckdb -c "select 42"
          - os: macos-latest
            name: macOS (staged)
            command: |
              DUCKDB_STAGED=c99ade5cb6/v2.0.0-alpha38367 bash install.sh
              test -x ~/.duckdb/cli/v2.0.0-alpha38367/duckdb
              ~/.duckdb/cli/latest/duckdb -c "select 42"
          - os: windows-latest
            name: Windows (stable)
            command: |
              ./install.ps1
              $sh = New-Object -ComObject WScript.Shell
              $target = $sh.CreateShortcut("$Home\Desktop\DuckDB.lnk").TargetPath
              & $target -c "select 42"
          - os: windows-latest
            name: Windows (staged)
            command: |
              $env:DUCKDB_STAGED = "c99ade5cb6/v2.0.0-alpha38367"
              ./install.ps1
              & "$env:LOCALAPPDATA\duckdb\cli\v2.0.0-alpha38367\duckdb.exe" -c "select 42"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7

    - name: Test install script on ${{ matrix.name }}
      run: ${{ matrix.command }}

  upload:
    needs: [test]
    runs-on: ubuntu-slim
    if: github.repository == 'duckdb/duckdb-install-scripts' && github.ref_name == 'main'

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install
        shell: bash
        run: pip install awscli

      - name: Upload
        env:
          AWS_ENDPOINT_URL: ${{ secrets.DUCKDB_INSTALL_S3_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DUCKDB_INSTALL_S3_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DUCKDB_INSTALL_S3_SECRET }}

        shell: bash
        run: |
          aws s3 cp install.sh s3://duckdb-install/
          aws s3 cp install.ps1 s3://duckdb-install/
